server:
  servlet:
    context-path: /dddsample
  error:
    include-message: always

cxf:
  path: /ws

logging:
  level:
    net.sf.ehcache.config.ConfigurationFactory: error
    web: info
    sql: info


uploadDirectory: /tmp/upload
parseFailureDirectory: /tmp/failed

brokerUrl: "vm://localhost?broker.persistent=false&broker.useJmx=false"

spring:
  dataSource:
    url: jdbc:hsqldb:mem:dddsample
    username: sa
    password: ""
    driver-class-name: org.hsqldb.jdbcDriver